ktor:
    application:
        modules:
            - ru.guap.ApplicationKt.module
    deployment:
        port: 3000
postgres:
  url: "jdbc:postgresql://localhost:5432/guap"
  driver: "org.postgresql.Driver"
  user: admin
  password: admin