CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL,

  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  vk_id BIGINT NOT NULL,
  photo TEXT NOT NULL,
  registered DATE NOT NULL DEFAULT CURRENT_DATE,
  show_onboarding BOOLEAN NOT NULL DEFAULT TRUE,

  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),

  PRIMARY KEY (id)
);